<a href="https://colab.research.google.com/github/Prajnaa002/Applied_Machine_Learning/blob/main/AML_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import scipy
print('scipy: %s' % scipy.__version__)

scipy: 1.16.3


In [ ]:
import numpy
print('numpy: %s' % numpy.__version__)

numpy: 2.0.2


In [ ]:
import pandas
print('pandas: %s' % pandas.__version__)

pandas: 2.2.2


In [ ]:
import statsmodels
print('statsmodels: %s' % statsmodels.__version__)

statsmodels: 0.14.6


In [ ]:
#scikit-learn
import sklearn
print('sklearn: %s' % sklearn.__version__)

sklearn: 1.6.1


##NUMERICAL PYTHON (NUMPY)

In [ ]:
import numpy as np

In [ ]:
#creating array
#create a list and convert into numpy array
mylist= [1,2,3]


In [ ]:
#just pass in a list directly
y=np.array([4,5,6])
y

array([4, 5, 6])

In [ ]:
#just pass in a list directly
m =np.array([[4,5,6],[7,8,9],[1,2,3]])
m

array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [ ]:
#to find the dimensions of the array(rows,columns)
m.shape

(3, 3)

In [ ]:
n= np.arange(0,32,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [ ]:
import numpy as np
n= np.arange(0,30,2)
n= n.reshape(3,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [ ]:
lspace= np.linspace(0,10,9)
lspace

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [ ]:
lspace.resize(3,3)
lspace

array([[ 0.  ,  1.25,  2.5 ],
       [ 3.75,  5.  ,  6.25],
       [ 7.5 ,  8.75, 10.  ]])

In [ ]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
num = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
num

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
type(num)

numpy.matrix

In [ ]:
print("Main diagnol elements: \n", np.diag(num))
print("diagonal elemenst above diagonal element: \n", np.diag(num,1))
print("diagonal elemenst below diagonal element: \n", np.diag(num,-1))
print("diagonal elemenst one step above diagonal element: \n", np.diag(num,2))
print("diagonal elemenst one step below diagonal element: \n", np.diag(num,-2))

Main diagnol elements: 
 [1 5 9]
diagonal elemenst above diagonal element: 
 [2 6]
diagonal elemenst below diagonal element: 
 [4 8]
diagonal elemenst one step above diagonal element: 
 [3]
diagonal elemenst one step below diagonal element: 
 [7]


In [ ]:
np.array([1,2,3] * 4)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
np.repeat([4,5,6],4)

array([4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6])

In [ ]:
p= np.ones([3,3], int)
p

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.vstack([p,2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [ ]:
np.vstack([p,2*p,3*p])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [ ]:
np.hstack([p,2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [ ]:
np.hstack([p,2*p,3*p])

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [1, 1, 1, 2, 2, 2, 3, 3, 3],
       [1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [ ]:
#operations
x= np.array([1,2,3])
y= np.array([4,5,6])
print(x)
print(y)

[1 2 3]
[4 5 6]


In [ ]:
print(x+y) #elementwise addition [1,2,3] * [4,5,6]
print(x-y) #elementwise subtraction [1,2,3] * [4,5,6]
print(x*y) #elementwise multiplication [1,2,3] * [4,5,6]
print(x/y) #elementwise division [1,2,3] * [4,5,6]
print(x**y) #elementwise power [1,2,3] * [4,5,6]


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [ ]:
print(x@y)  #elementwise dot product [1,2,3] * [4,5,6]
x.dot(y) #dot product 1*4 + 2*5+ 3*6

32


np.int64(32)

In [ ]:
z= np.array([y,y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [ ]:
print(len(z))

2


In [ ]:
z= np.array([y,y**2])
z.shape

(2, 3)

In [ ]:
z.T #transpose

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [ ]:
z.T.shape

(3, 2)

In [ ]:
z.dtype

dtype('int64')

In [ ]:
z= z.astype('f') # use .astype tp cast top a specific type
z.dtype

dtype('float32')

In [ ]:
#math functions

a = np.array([-4,-2,4,4,8])
a.sum()

np.int64(10)

In [ ]:
a.max()

np.int64(8)

In [ ]:
a.min()

np.int64(-4)

In [ ]:
a.mean()

np.float64(2.0)

In [ ]:
a.std()

np.float64(4.381780460041329)

In [ ]:
#argmax and argmin returns the index of the maximm and the minimum values in the array
a.argmax()

np.int64(4)

In [ ]:
a.argmin()

np.int64(0)

In [ ]:
#indexing/slicing'

import numpy as np
s= np.arange(100)

print(s)
s.reshape(10,10)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
s= np.arange(6) ** 2
s

array([ 0,  1,  4,  9, 16, 25])

In [ ]:
#use bracket to gvet the value at a specific index
s[0],s[4],s[-1]

(np.int64(0), np.int64(16), np.int64(25))

In [ ]:
#use : to indicatew a range.
#array[start:stop]
#leavinbg statr and stop empty will default to beginning/end of the array
s[1:5]

array([ 1,  4,  9, 16])

In [ ]:
s = np.arange(13) ** 2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [ ]:
s[-4:]

array([ 81, 100, 121, 144])

In [ ]:
#[start:stop:stepsoixe]
s[-5::-2]

array([64, 36, 16,  4,  0])

In [ ]:
s[-5:-2]

array([ 64,  81, 100])

In [ ]:
r=r= np.arange(100)
r.resize(10,10)
r

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
#use bracket notation to slice: array[row,column]
r[3,4]

np.int64(34)

In [ ]:
r[2,1:4]

array([21, 22, 23])

In [ ]:
r[3,3:6]

array([33, 34, 35])

In [ ]:
r[:3,:-1] # here we are selecting all the rows up to(and not including) row 2 , and all the columns

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [20, 21, 22, 23, 24, 25, 26, 27, 28]])

In [ ]:
r[-1,::2] # slice of last row, aand only every other element

array([90, 92, 94, 96, 98])

In [ ]:
r[r>30]# we can perform conditional indexing

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
       65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
       82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,
       99])

In [ ]:
r[r>30] = 30 # we arew assigning all values in the array that are greater than 30  to the value
r

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30]])

In [ ]:
#copying the data
#r2 is a slice of r
r2= r[:3,:3]
r2

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [ ]:
#set this slice value to zero([:] selects the entire array)
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
r # r has also been changed

array([[ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0, 23, 24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30]])

In [ ]:
#to avoid this, use r.copy to create a copy that will not affect
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0, 23, 24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30]])

In [ ]:
r_copy[:] = 10 #
print(r_copy, '\n')
print(r)

[[10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5  6  7  8  9]
 [ 0  0  0 13 14 15 16 17 18 19]
 [ 0  0  0 23 24 25 26 27 28 29]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]]


In [ ]:
#iterating over arrays
# create a new array 4 by 3 array of random numbers 0-9
test = np.random.randint(0,10,(4,3))
test

array([[5, 7, 7],
       [5, 0, 2],
       [1, 4, 8],
       [3, 5, 6]])

In [ ]:
#iterate by row
for row in test:
  print(row)

[5 7 7]
[5 0 2]
[1 4 8]
[3 5 6]


In [ ]:
for i in range(len(test)):
  print(test[i])


[5 7 7]
[5 0 2]
[1 4 8]
[3 5 6]


In [ ]:
for i,row in enumerate(test): #iterate by row and index
  print('row',i,'is',row)

row 0 is [5 7 7]
row 1 is [5 0 2]
row 2 is [1 4 8]
row 3 is [3 5 6]


In [ ]:
test2= test**2 # use zip to iterate over multiple iterables
test2

array([[25, 49, 49],
       [25,  0,  4],
       [ 1, 16, 64],
       [ 9, 25, 36]])

In [ ]:
for i,j in zip(test, test2):
  print(i,'+',j,'=',i+j)

[5 7 7] + [25 49 49] = [30 56 56]
[5 0 2] + [25  0  4] = [30  0  6]
[1 4 8] + [ 1 16 64] = [ 2 20 72]
[3 5 6] + [ 9 25 36] = [12 30 42]


In [ ]:
#axis= 0 -> column-wise operation
#axis= 1 -> row-wise operation

In [ ]:
marks= np.array([
    [89,90,97],
    [56,98,67],
    [45,88,99],
    [77,99,66]
])

student_total = np.sum(marks, axis=1)
print(student_total)
student_average = np.mean(marks, axis=1)
print(student_average)
subject_average = np.mean(marks, axis=0)
print(subject_average)
highest_studnet = np.argmax(student_total)
print(highest_studnet)

[276 221 232 242]
[92.         73.66666667 77.33333333 80.66666667]
[66.75 93.75 82.25]
0


# NUMPY ASSIGNMENT

1. Create a constant array



		# Prints "[[ 7.  7.]
                #  [ 7.  7.]]"

create a 2D array (2 rows, 2 columns) filled with 7


In [ ]:
arr = np.full((2, 2), 7.0)
print(arr)

[[7. 7.]
 [7. 7.]]


2. Create an array filled with random values


           # Might print "[[ 0.91940167  0.08143941]
                           [ 0.68744134  0.87236687]]"

In [ ]:
test = np.random.rand(2,2)
test

array([[0.37880113, 0.12877448],
       [0.66637202, 0.7738091 ]])

3. Create a NumPy array containing the numbers from 10 to 50. Display:

The array

Number of elements

Shape

Dimension

Data type

In [ ]:
array = np.arange(10, 51)

print("The array:", array)
print("Number of elements:", array.size)
print("Shape:", array.shape)
print("Dimension:", array.ndim)
print("Data type:", array.dtype)

The array: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
Number of elements: 41
Shape: (41,)
Dimension: 1
Data type: int64


4. Using NumPy, create:

A 1D array containing 10 zeros

A 3 × 3 array containing ones

A 4 × 4 identity matrix

An array containing numbers from 5 to 50 with a step size of 5.


In [ ]:
a= np.zeros(10)
b= np.ones((3, 3),int)
c= np.eye(4)
d= np.arange(5, 51, 5)

print(a.astype(int))

print(b)

print(c.astype(int))

print(d)

[0 0 0 0 0 0 0 0 0 0]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[ 5 10 15 20 25 30 35 40 45 50]


5. Create an array containing numbers from 1 to 24. Reshape it into:

4 × 6

6 × 4

2 × 3 × 4

Display the shape and ndim of each result.


In [ ]:
array1 = np.arange(1, 25)
print(array1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [ ]:
i= array1.reshape(4, 6)
i

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [ ]:
j= array1.reshape(6, 4)
j

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [ ]:
k= array1.reshape(2,3,4)
k

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [ ]:
print("Shape of i: "+ str(i.shape) + " Dimension of i:"+ str(i.ndim))
print("Shape of j: "+ str(j.shape)+ " Dimension of j:"+ str(j.ndim))
print("Shape of k: "+ str(k.shape)+ " Dimension of k:"+ str(k.ndim))

Shape of i: (4, 6) Dimension of i:2
Shape of j: (6, 4) Dimension of j:2
Shape of k: (2, 3, 4) Dimension of k:3


6. Consider: marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])

Write NumPy statements to display:

First element

Last element

Third element

First four elements

Last three elements

In [ ]:
marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])
print(marks[0])
print(marks[-1])
print(marks[2])
print(marks[:4])
print(marks[-3:])

78
81
92
[78 85 92 67]
[73 95 81]


7. Create:
a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 10, 15, 20, 25])

Calculate:

a + b

a - b

a * b

a / b

Square of every element in a

In [ ]:
a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 10, 15, 20, 25])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2)

[15 30 45 60 75]
[ 5 10 15 20 25]
[  50  200  450  800 1250]
[2. 2. 2. 2. 2.]
[ 100  400  900 1600 2500]


8. Given:
salary = np.array([25000, 32000, 28000, 45000,
                   50000, 38000, 42000, 30000])

Find:

Total salary

Average salary

Highest salary

Lowest salary

Median salary

Standard deviation

In [ ]:
salary = np.array([25000, 32000, 28000, 45000, 50000, 38000, 42000, 30000])
salary_sum = np.sum(salary)
print("Total salary:", salary_sum)
salary_average = np.mean(salary)
print("Average salary:", salary_average)
salary_max = np.max(salary)
print("Highest salary:", salary_max)
salary_min = np.min(salary)
print("Lowest salary:", salary_min)
salary_median = np.median(salary)
print("Median salary:", salary_median)
salary_std = np.std(salary)
print("Standard Deviation:", salary_median)

Total salary: 290000
Average salary: 36250.0
Highest salary: 50000
Lowest salary: 25000
Median salary: 35000.0
Standard Deviation: 35000.0


9. Given: marks = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84])

Using NumPy boolean indexing, find:

Marks greater than 75
Marks between 50 and 80

Number of students who scored below 50

Percentage of students who scored 60 or above

Do not use a Python for loop.

In [ ]:
marks = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84])
# marks greater than 75
greater_than_75 = marks>75
print(marks[greater_than_75])
# marks between 50 and 80
between_50_and_80 = (marks>50) & (marks<80)
print(marks[between_50_and_80])
#Number of students who scored below 50
scored_below_50 = marks>50
print( "Marks scored below 50: "+ str(marks[scored_below_50]))
print("Number of students who scored below 50 : " + str((len(marks[scored_below_50]))))
#Percentage of students who scored 60 or above
scored_above_60 = marks>60
print( "Marks scored above 60: "+ str(marks[scored_above_60]))
print("Number of students who scored above 60 : " + str((len(marks[scored_above_60]))))
percentage = (len(marks[scored_above_60])/len(marks))*100
print("Percentage of students who scored 60 or above : " + str(percentage))


[78 89 90 76 84]
[78 67 55 76]
Marks scored below 50: [78 89 67 90 55 76 84]
Number of students who scored below 50 : 7
Marks scored above 60: [78 89 67 90 76 84]
Number of students who scored above 60 : 6
Percentage of students who scored 60 or above : 60.0


10. The following array contains marks of four students in three subjects:

marks = np.array([
    [80, 75, 90],
    [65, 70, 72],
    [88, 92, 85],
    [55, 60, 58]
])

Calculate:

Total marks of each student

Average marks of each student

Average marks in each subject

Student with the highest total

Highest mark in each subject.

In [ ]:
marks = np.array([
    [80, 75, 90],
    [65, 70, 72],
    [88, 92, 85],
    [55, 60, 58]
])
student_total = np.sum(marks, axis=1)
print(student_total)
student_average = np.mean(marks, axis=1)
print(student_average)
subject_average = np.mean(marks, axis=0)
print(subject_average)
highest_student = np.argmax(student_total)
print(highest_student)
highest_subject = np.max(marks, axis=0)
print(highest_subject)


[245 207 265 173]
[81.66666667 69.         88.33333333 57.66666667]
[72.   74.25 76.25]
2
[88 92 90]


11. Create:

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

Perform:

Matrix addition

Element-wise multiplication

Matrix multiplication

Transpose of A.

explain the difference between:
A * B and A @ B

In [ ]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print(A+B)
print(A*B)
print(A@B)
print(A.T)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


12. Daily temperatures for two weeks are:

temperature = np.array([
    31, 32, 33, 35, 36, 34, 32,
    30, 29, 31, 33, 35, 37, 36
])

Find:

Mean temperature

Maximum and minimum temperatures

Number of days above the average temperature

Temperatures greater than 34°C

Difference between maximum and minimum

Standard deviation

In [ ]:
temperature = np.array([
    31, 32, 33, 35, 36, 34, 32,
    30, 29, 31, 33, 35, 37, 36
])

#Mean temperature
mean_temperature = np.mean(temperature)
print("Mean temperature:", mean_temperature)

#Maximum and minimum temperatures
max_temperature = np.max(temperature)
min_temperature = np.min(temperature)
print("Maximum temperature:", max_temperature)
print("Minimum temperature:", min_temperature)

#Number of days above the average temperature
days_above_average = np.sum(temperature > mean_temperature)
print("Number of days above the average temperature:", days_above_average)

#Temperatures greater than 34°C
temperature_above_34 = temperature>34
print( "Temperatures greater than 34°C : "+ str(temperature[temperature_above_34]))

#Difference between maximum and minimum
temperature_difference = max_temperature - min_temperature
print("Difference between maximum and minimum:", temperature_difference)

#Standard deviation
temperature_std = np.std(temperature)
print("Standard Deviation:", temperature_std)


Mean temperature: 33.142857142857146
Maximum temperature: 37
Minimum temperature: 29
Number of days above the average temperature: 6
Temperatures greater than 34°C : [35 36 35 37 36]
Difference between maximum and minimum: 8
Standard Deviation: 2.356060357495806


13. Monthly sales of a company are:
sales = np.array([
    12000, 15000, 17000, 14000,
    18000, 21000, 19000, 22000,
    25000, 23000, 26000, 28000
])

Determine:

Total annual sales

Average monthly sales

Month with the highest sales

Month with the lowest sales

Number of months with sales above ₹20,000

Percentage increase from January to December

Hint: Remember that NumPy indexing starts at 0, while month numbering normally starts at 1.


In [ ]:
sales = np.array([
    12000, 15000, 17000, 14000,
    18000, 21000, 19000, 22000,
    25000, 23000, 26000, 28000
])

#Total annual sales
total_annual_sales = np.sum(sales)
print("Total annual sales:", total_annual_sales)

#Average monthly sales
average_monthly_sales = np.mean(sales)
print("Average monthly sales:", average_monthly_sales)

#Month with the highest sales
highest_sales_month = np.argmax(sales)
print("Month with the highest sales:", highest_sales_month)

lowest_sales_month = np.argmin(sales)
print("Month with the lowest sales:", lowest_sales_month)

Total annual sales: 240000
Average monthly sales: 20000.0
Month with the highest sales: 11
Month with the lowest sales: 0


14. Consider marks of five students in four subjects:

marks = np.array([
    [78, 85, 90, 88],
    [65, 70, 72, 68],
    [92, 88, 95, 91],
    [55, 60, 58, 62],
    [80, 75, 82, 79]
])

Write a NumPy program that calculates:

Total marks of every student

Average of every student

Average mark for every subject

Highest-scoring student

Lowest-scoring student

Students whose average is greater than 80

Overall class average

Then assign a performance category based on average:

|  Average | Category          |
| -------: | ----------------- |
|     ≥ 85 | Excellent         |
| 70–84.99 | Good              |
| 50–69.99 | Average           |
|     < 50 | Needs Improvement |

Challenge: Try assigning these categories using np.where() or np.select() instead of a Python loop.

In [ ]:
marks = np.array([
    [78, 85, 90, 88],
    [65, 70, 72, 68],
    [92, 88, 95, 91],
    [55, 60, 58, 62],
    [80, 75, 82, 79]
])

student_total_marks = np.sum(marks, axis=1)
print("Total marks of each student:", student_total_marks)

student_average_marks = np.mean(marks, axis=1)
print("Average marks of each student:", student_average_marks)

subject_average_marks = np.mean(marks, axis=0)
print("Average marks in each subject:", subject_average_marks)

highest_scoring_student_index = np.argmax(student_total_marks)
print("Highest-scoring student (index, 0-based):", highest_scoring_student_index)

lowest_scoring_student_index = np.argmin(student_total_marks)
print("Lowest-scoring student (index, 0-based):", lowest_scoring_student_index)

students_avg_greater_than_80 = marks[student_average_marks > 80]
print("Marks of students whose average is greater than 80:\n", students_avg_greater_than_80)

overall_class_average = np.mean(marks)
print("Overall class average:", overall_class_average)

conditions = [
    student_average_marks >= 85,
    (student_average_marks >= 70) & (student_average_marks < 85),
    (student_average_marks >= 50) & (student_average_marks < 70),
    student_average_marks < 50
]
choices = ['Excellent', 'Good', 'Average', 'Needs Improvement']

performance_categories = np.select(conditions, choices, default='Unknown')
print("\nPerformance categories for each student:", performance_categories)

Total marks of each student: [341 275 366 235 316]
Average marks of each student: [85.25 68.75 91.5  58.75 79.  ]
Average marks in each subject: [74.  75.6 79.4 77.6]
Highest-scoring student (index, 0-based): 2
Lowest-scoring student (index, 0-based): 3
Marks of students whose average is greater than 80:
 [[78 85 90 88]
 [92 88 95 91]]
Overall class average: 76.65

Performance categories for each student: ['Excellent' 'Average' 'Excellent' 'Average' 'Good']


15. Generate 20 random integers between 1 and 100.


In [ ]:
random_integers = np.random.randint(1, 101, 20)
print(random_integers)

[63 93 63 15 11 71 63 87 48  1 39 39 72 97 55 50 30 88 77 75]


16. Find all even numbers from the generated array.


In [ ]:
even_number = random_integers[random_integers % 2 == 0]
print("Even numbers from the array: ",even_number)

Even numbers from the array:  [48 72 50 30 88]


17. Replace values below 50 with 0.

In [ ]:
random_integers[random_integers < 50] = 0
print("Array after replacing values below 50 with 0:", random_integers)

Array after replacing values below 50 with 0: [63 93 63  0  0 71 63 87  0  0  0  0 72 97 55 50  0 88 77 75]


18. Sort the array in ascending and descending order.

In [ ]:
sorted_ascending = np.sort(random_integers)
print("Array sorted in ascending order:", sorted_ascending)

sorted_descending = sorted_ascending[::-1]
print("Array sorted in descending order:", sorted_descending)

Array sorted in ascending order: [ 0  0  0  0  0  0  0 50 55 63 63 63 71 72 75 77 87 88 93 97]
Array sorted in descending order: [97 93 88 87 77 75 72 71 63 63 63 55 50  0  0  0  0  0  0  0]


19. Find unique values and their frequencies.

In [ ]:
unique_values, counts = np.unique(random_integers, return_counts=True)
print("Unique values:", unique_values)
print("Frequencies:", counts)

Unique values: [ 0 50 55 63 71 72 75 77 87 88 93 97]
Frequencies: [7 1 1 3 1 1 1 1 1 1 1 1]


20. Create a 5 × 5 random matrix and calculate row-wise and column-wise means.

In [ ]:
random_matrix = np.random.randint(0, 100, size=(5, 5))
print("5x5 Random Matrix:\n", random_matrix)

row_wise_mean = np.mean(random_matrix, axis=1)
print("\nRow-wise Means:", row_wise_mean)

col_wise_mean = np.mean(random_matrix, axis=0)
print("Column-wise Means:", col_wise_mean)

5x5 Random Matrix:
 [[11 50 74 79 88]
 [65 28 67 98 13]
 [65 64 55 21 84]
 [83 56  9 52 30]
 [50 74 19 95 48]]

Row-wise Means: [60.4 54.2 57.8 46.  57.2]
Column-wise Means: [54.8 54.4 44.8 69.  52.6]


21. Take your own example to normalize an array.



In [ ]:
# Take your own example to normalize an array.
# Min-Max Normalization: (x - min(x)) / (max(x) - min(x))

my_array_to_normalize = np.array([10, 20, 30, 40, 50, 100])
print("Original array for normalization:", my_array_to_normalize)

min_val = np.min(my_array_to_normalize)
max_val = np.max(my_array_to_normalize)

normalized_array = (my_array_to_normalize - min_val) / (max_val - min_val)
print("Normalized array:", normalized_array)

Original array for normalization: [ 10  20  30  40  50 100]
Normalized array: [0.         0.11111111 0.22222222 0.33333333 0.44444444 1.        ]


22. use your own data to standardize an array.

In [ ]:
#Use your own data to standardize an array.
# Standardization: (x - mean(x)) / std(x)

my_array_to_standardize = np.array([5, 10, 15, 20, 25, 30])
print("Original array for standardization:", my_array_to_standardize)

mean_val = np.mean(my_array_to_standardize)
std_dev = np.std(my_array_to_standardize)

standardized_array = (my_array_to_standardize - mean_val) / std_dev
print("Standardized array:", standardized_array)

Original array for standardization: [ 5 10 15 20 25 30]
Standardized array: [-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]


23. Create a NumPy array containing 100 random exam marks and determine how many students fall into the ranges 0–39, 40–59, 60–79, and 80–100.

In [ ]:
exam_marks = np.random.randint(0, 101, 100)
print("100 Random Exam Marks:\n", exam_marks)

# Count students in each range
range_0_39 = np.sum((exam_marks >= 0) & (exam_marks <= 39))
range_40_59 = np.sum((exam_marks >= 40) & (exam_marks <= 59))
range_60_79 = np.sum((exam_marks >= 60) & (exam_marks <= 79))
range_80_100 = np.sum((exam_marks >= 80) & (exam_marks <= 100))

print("\nNumber of students in range 0-39:", range_0_39)
print("Number of students in range 40-59:", range_40_59)
print("Number of students in range 60-79:", range_60_79)
print("Number of students in range 80-100:", range_80_100)

100 Random Exam Marks:
 [ 85  72  68  88  74  44  86  98  38  62  28  87  85  88  26  74  88  39
  97  77  33  94  39  11  59   0  96  54  17  44  93  67  56  80  46  86
  60  43   7 100  92  16   8  82  38  57  19  77  66  30  64  71  84  29
  78  82  93  89  14  88  82  93  20   6   3  86  43  30  59  61  32  20
   0  58   0  83  14   8   7  34   5  32  52  38  15  76  33  85  92  67
  64  12  39  38  86 100  66  67  61  49]

Number of students in range 0-39: 37
Number of students in range 40-59: 13
Number of students in range 60-79: 20
Number of students in range 80-100: 30


24. Compare the time required to multiply 1,000,000 numbers using a Python list and a NumPy array.


In [ ]:
import time

SIZE = 1_000_000

# Python list multiplication
python_list1 = list(range(SIZE))
python_list2 = list(range(SIZE))

start_time = time.time()
python_result = [a * b for a, b in zip(python_list1, python_list2)]
end_time = time.time()
python_time = end_time - start_time
print(f"Time taken for Python list multiplication: {python_time:.6f} seconds")

# NumPy array multiplication
numpy_array1 = np.arange(SIZE)
numpy_array2 = np.arange(SIZE)

start_time = time.time()
numpy_result = numpy_array1 * numpy_array2
end_time = time.time()
numpy_time = end_time - start_time
print(f"Time taken for NumPy array multiplication: {numpy_time:.6f} seconds")

print(f"\nNumPy is approximately {python_time / numpy_time:.2f} times faster than Python lists for this operation.")

Time taken for Python list multiplication: 0.100424 seconds
Time taken for NumPy array multiplication: 0.004440 seconds

NumPy is approximately 22.62 times faster than Python lists for this operation.
